import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";
import QueryProvider from "@/lib/queryProvider";
import ScrollToTopButton from "@/components/scrollToTopButton";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "POKÉMON - Franco Vallone",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >

        <QueryProvider>

            <header className="relative z-50">
                <NavBar/>
            </header>

            <main className="flex-grow relative pt-20">
                <div
                    className="absolute inset-0 opacity-10 -z-10"
                    style={{
                        backgroundImage: "url('/diagonal-stripes.svg')",
                        backgroundRepeat: 'repeat',
                        backgroundSize: '300px',
                    }}
                />

                <div className="relative z-0">
                    {children}
                    <ScrollToTopButton/>
                </div>
            </main>

            <Footer/>

        </QueryProvider>
        </body>
        </html>
    );
}