import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";
import QueryProvider from "@/lib/queryProvider";
import ScrollToTopButton from "@/components/scrollToTopButton";
import {Providers} from "./providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "POKÉDEX - Franco Vallone",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" className="dark">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
        <Providers>
            <QueryProvider>
                <header className="relative z-50">
                    <NavBar/>
                </header>

                <main className="flex-grow relative pt-20 z-10">
                    {children}
                    <ScrollToTopButton/>
                </main>

                <Footer/>
            </QueryProvider>
        </Providers>
        </body>
        </html>
    );
}